### ISSUE TITLE
sys/mman.h: No such file or directory

### ISSUE THREAD

**Issue by bgeVam** [boyska/cryptapult#1]
Hi, I am currently trying your cryptapult, unfortunatley a header file is missing in newlib:

crypta.c:8:22: fatal error: sys/mman.h: No such file or directory

is there any other library containing this file?

currently using newlib 2.4

**Comment by boyska** [comment]
GeorgB:
>Hi, I am currently trying your cryptapult, unfortunatley a header file is missing in newlib:
>crypta.c:8:22: fatal error: sys/mman.h: No such file or directory
>
>is there any other library containing this file?
>currently using newlib 2.4

perhaps newlib is the cause; I only tested cryptapult with glibc. mman is
needed for mmap. If newlib provides mman implements mmap on a different
header file, just add an #ifdef for it
